version: 2
jobs:
  test:
    docker:
      - image: circleci/openjdk:8
    steps:
      - checkout
      - run:
          -name: Run tests
          -command: ./gradlew test
workflows:
  version: 2
  test:
    jobs:
      - test